#!/bin/bash

### BEGIN INIT INFO
# Provides:           PiDACS server
# Required-Start:     $local_fs $syslog $network
# Required-Stop:      $local_fs $syslog $network
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  PiDACS server
# Description:        PiDACS server
### END INIT INFO

# Raspberry Pi Data Acquisition and Control System (PiDACS)

# PiDACS server daemon script (pidacsd).

cmd=$1
case $cmd in
    start)
        sudo /usr/local/bin/pidacs -l 2>&1 &
        ;;
    stop)
        sudo killall pidacs
        ;;
    *)
        echo 'Usage /etc/init.d/pidacsd {start|stop}'
        exit 1
        ;;
esac
